// Stamp src/ad.html into the three renderable HyperFrames compositions.
//   node build.mjs [169|sq|vt]   -> index.html at 1920x1080 (default), 1080x1080 or 1080x1920
// HyperFrames allows one root composition per project, so each aspect is built in turn
// into index.html and rendered; the committed index.html is the 16:9 master.
// Scene timing is authored in beats (data-b="from,to" at 125 BPM) and written out
// as data-start / data-duration in seconds, so every cut lands on a beat.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const BEAT = 60 / 125;
const TOTAL_BEATS = 128.5;
const s = (b) => +(b * BEAT).toFixed(4);

const src = readFileSync(join(HERE, "src/ad.html"), "utf8");
const wordmark = readFileSync(join(HERE, "assets/predge-wordmark.svg"), "utf8").replace(/<\?xml[^>]*>/, "").replace(/<title>[^<]*<\/title>/, "").replace(/<!--[\s\S]*?-->/g, "");
const cursor = `<svg viewBox="0 0 24 24"><path d="M3 2 L3 19.5 L7.6 15.4 L10.9 22.2 L14 20.8 L10.8 14.2 L17.2 14.2 Z" fill="#1c1c1c" stroke="#fff" stroke-width="1.4" stroke-linejoin="round"/></svg>`;

const sizes = { "169": [1920, 1080], sq: [1080, 1080], vt: [1080, 1920] };
const ar = process.argv[2] || "169";
if (!sizes[ar]) throw new Error("aspect must be 169 | sq | vt");
const file = "index.html";
{
  const [w, h] = sizes[ar];
  let out = src
    .replaceAll("__W__", String(w)).replaceAll("__H__", String(h)).replaceAll("__AR__", ar)
    .replaceAll("__TOTAL__", String(s(TOTAL_BEATS)))
    .replaceAll("__WORDMARK__", wordmark).replaceAll("__CURSOR__", cursor)
    .replace(/data-b="(\d+(?:\.\d+)?),(\d+(?:\.\d+)?)"/g, (_, a, b) => `data-start="${s(+a)}" data-duration="${s(+b - +a)}"`);
  out = out.replace(/<!-- Source template\.[\s\S]*?-->/, "<!-- GENERATED by build.mjs from src/ad.html. Do not edit. -->");
  writeFileSync(join(HERE, file), out);
  console.log(file, w + "x" + h, s(TOTAL_BEATS) + "s");
}
